# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui104.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(650, 850))
        Dialog.setMaximumSize(QtCore.QSize(650, 850))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../manyPicture/else/123123.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.output = QtWidgets.QLabel(Dialog)
        self.output.setGeometry(QtCore.QRect(30, 20, 551, 41))
        self.output.setStyleSheet("font: 12pt \"新細明體\";")
        self.output.setObjectName("output")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(30, 110, 431, 41))
        self.lineEdit.setStyleSheet("font: 18pt \"新細明體\";")
        self.lineEdit.setMaxLength(100)
        self.lineEdit.setObjectName("lineEdit")
        self.activate = QtWidgets.QPushButton(Dialog)
        self.activate.setGeometry(QtCore.QRect(470, 110, 121, 41))
        self.activate.setStyleSheet("font: 12pt \"新細明體\";")
        self.activate.setObjectName("activate")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 60, 101, 41))
        self.pushButton_2.setStyleSheet("font: 12pt \"新細明體\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.salaryyes = QtWidgets.QCheckBox(Dialog)
        self.salaryyes.setGeometry(QtCore.QRect(220, 180, 101, 41))
        self.salaryyes.setStyleSheet("font: 12pt \"新細明體\";")
        self.salaryyes.setChecked(True)
        self.salaryyes.setObjectName("salaryyes")
        self.salaryno = QtWidgets.QCheckBox(Dialog)
        self.salaryno.setGeometry(QtCore.QRect(330, 180, 101, 41))
        self.salaryno.setStyleSheet("font: 12pt \"新細明體\";")
        self.salaryno.setChecked(True)
        self.salaryno.setObjectName("salaryno")
        self.filter = QtWidgets.QPushButton(Dialog)
        self.filter.setGeometry(QtCore.QRect(440, 180, 111, 41))
        self.filter.setStyleSheet("font: 12pt \"新細明體\";")
        self.filter.setObjectName("filter")
        self.jobresult = QtWidgets.QTextBrowser(Dialog)
        self.jobresult.setGeometry(QtCore.QRect(30, 240, 581, 611))
        self.jobresult.setObjectName("jobresult")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 180, 171, 41))
        self.comboBox.setStyleSheet("font: 12pt \"新細明體\";")
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "104_jobui       by yongenyang, Josh1216"))
        self.output.setText(_translate("Dialog", "未連線，請先連線"))
        self.activate.setText(_translate("Dialog", "啟動！！！"))
        self.pushButton_2.setText(_translate("Dialog", "嘗試連線"))
        self.salaryyes.setText(_translate("Dialog", "有寫薪資"))
        self.salaryno.setText(_translate("Dialog", "待遇面議"))
        self.filter.setText(_translate("Dialog", "篩選！"))
        self.comboBox.setItemText(0, _translate("Dialog", "選擇地區"))
