# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TC100_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(650, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(650, 500))
        Dialog.setMaximumSize(QtCore.QSize(650, 500))
        self.servoOnOff = QtWidgets.QPushButton(Dialog)
        self.servoOnOff.setGeometry(QtCore.QRect(120, 90, 161, 61))
        self.servoOnOff.setStyleSheet("font: 23pt \"Agency FB\";")
        self.servoOnOff.setObjectName("servoOnOff")
        self.turnToZero = QtWidgets.QPushButton(Dialog)
        self.turnToZero.setGeometry(QtCore.QRect(120, 220, 161, 61))
        self.turnToZero.setStyleSheet("font: 23pt \"Agency FB\";")
        self.turnToZero.setObjectName("turnToZero")
        self.inPut = QtWidgets.QPushButton(Dialog)
        self.inPut.setGeometry(QtCore.QRect(120, 350, 161, 61))
        self.inPut.setStyleSheet("font: 23pt \"Agency FB\";")
        self.inPut.setObjectName("inPut")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(300, 90, 171, 61))
        self.label.setStyleSheet("font: 23pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(470, 90, 51, 61))
        self.label_2.setStyleSheet("font: 23pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 40, 341, 51))
        self.label_3.setStyleSheet("font: 18pt \"Agency FB\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(310, 350, 151, 61))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 300, 341, 51))
        self.label_4.setStyleSheet("font: 18pt \"Agency FB\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(460, 350, 341, 51))
        self.label_5.setStyleSheet("font: 13pt \"Agency FB\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(0, 170, 371, 51))
        self.label_6.setStyleSheet("font: 18pt \"Agency FB\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(300, 220, 171, 61))
        self.label_7.setStyleSheet("font: 23pt \"Agency FB\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(470, 220, 151, 61))
        self.label_8.setStyleSheet("font: 15pt \"Agency FB\";")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.servoOnOff.setText(_translate("Dialog", "servo on/off"))
        self.turnToZero.setText(_translate("Dialog", "原點賦歸"))
        self.inPut.setText(_translate("Dialog", "位置確認"))
        self.label.setText(_translate("Dialog", "伺服狀態:"))
        self.label_2.setText(_translate("Dialog", "off"))
        self.label_3.setText(_translate("Dialog", "按按鈕啦,不按怎麼有反應"))
        self.label_4.setText(_translate("Dialog", "先輸入位置再按按鈕"))
        self.label_5.setText(_translate("Dialog", "<----位置輸入在這裡"))
        self.label_6.setText(_translate("Dialog", "就是回到原點,不然還能幹嘛"))
        self.label_7.setText(_translate("Dialog", "賦歸狀態:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
